
    create table Cancha (
        id_cancha integer generated by default as identity (start with 1),
        esta_iluminada boolean,
        nombre varchar(255),
        primary key (id_cancha)
    )

    create table Color (
        cod_color integer generated by default as identity (start with 1),
        descripcion varchar(255),
        primary key (cod_color)
    )

    create table Constructor (
        cod_constructor integer generated by default as identity (start with 1),
        domicilio integer,
        nombre varchar(255),
        primary key (cod_constructor)
    )

    create table Jugadores (
        id_jugador integer generated by default as identity (start with 1),
        apellido varchar(255),
        domicilo varchar(255),
        nacimiento integer,
        nombre varchar(255),
        primary key (id_jugador)
    )

    create table Paletas (
        cod_paleta integer generated by default as identity (start with 1),
        grosor integer,
        nombre varchar(255),
        primary key (cod_paleta)
    )

    create table Participacion (
        partido_id_partido integer not null,
        jugador_id_jugador integer not null,
        primary key (partido_id_partido, jugador_id_jugador)
    )

    create table Partidos (
        id_partido integer generated by default as identity (start with 1),
        fin_partido integer,
        inicio_partido integer,
        primary key (id_partido)
    )

    alter table Participacion 
        add constraint FK_5c53vc32mkiy9bj4kdpk11udp 
        foreign key (partido_id_partido) 
        references Partidos

    alter table Participacion 
        add constraint FK_ok0xruxsa70uaffkwimt9wvuk 
        foreign key (jugador_id_jugador) 
        references Jugadores
